CREATE TABLE cidade( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
      uf_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE uf( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1   , 
      sigla char  (2)   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE cidade ADD CONSTRAINT fk_cidade_1 FOREIGN KEY (uf_id) references uf(id); 
