[builder]
app_url = "https://app.madbuilder.com.br"
manager_url = "https://code.madbuilder.com.br"
services_url = "https://services.madbuilder.com.br"
version = "4.2"

[general]
timezone = America/Sao_Paulo
language = pt
application = starter
title = "starter"
require_terms = 0
theme = theme3
dialog_box_type = "bootstrap"
multiunit = 0
change_unit = 0
request_unit_after_login = 0
locale = pt-BR
token = 3132b4a91ce7c4b6c7874290b3d10855d0f3457d3d3683aa8e9cc1d6eaed6625f4b487
seed = 35fc9380df83052df611976372196aa8eb84cb17
rest_key = bc21120e490393fb289c4452d8ddd3a9fba28e58fca1fa12a150a7fff723
debug = 0
multi_lang = "0"
left_menu = "1"
top_menu = "0"
verify_messages_menu = "0"
verify_notifications_menu = "0"
default_units = ""
use_tabs = 0
store_tabs = 0
use_mdi_windows = 0
store_mdi_windows = 0
notification_login = 0
left_menu_modules = "1"
top_menu_modules = "1"
application_version = "Versão 1.0"
main_database = "starter"

;request_log_service = SystemRequestLogService
;request_log = 1
;request_log_types = cli,web,rest


multi_database = "0"

public_view = "0"
public_entry = "PublicView"
theme_mobile = theme4

[user_public_pages]


[permission]

user_register    = "0"  ; users may auto register
reset_password   = "0"  ; users may reset password
default_groups   = "2"  ; default groups for auto registered users
default_units    = "1"  ; default units for auto registered users
default_screen   = "10" ; default screen for auto registered users
single_user_session = 0



; Public classes, anyone (logged or not) has access
public_classes[] = PublicForm
public_classes[] = PublicView
public_classes[] = DatabaseInstall
public_classes[] = ExtensionsInstall
public_classes[] = PathInstall
public_classes[] = SummaryDatabaseInstall
public_classes[] = SystemModulesCheckView
public_classes[] = AdiantiMultiSearchService
public_classes[] = AdiantiUploaderService
public_classes[] = AdiantiAutocompleteService

